### ISSUE TITLE
USB install issues

### ISSUE THREAD

**Issue by Zeromark30** [XorTroll/Tinfoil#73]
```
Sending header...
Traceback (most recent call last):
  File "D:\Kyle\switch\tinfoil\usb_install_pc.py", line 151, in <module>
    send_nsp_list(nsp_dir, out_ep)
  File "D:\Kyle\switch\tinfoil\usb_install_pc.py", line 106, in send_nsp_list
    out_ep.write(b'TUL0') # Tinfoil USB List 0
  File "D:\Kyle\Python37\lib\site-packages\usb\core.py", line 387, in write
    return self.device.write(self, data, timeout)
  File "D:\Kyle\Python37\lib\site-packages\usb\core.py", line 948, in write
    self.__get_timeout(timeout)
  File "D:\Kyle\Python37\lib\site-packages\usb\backend\libusb0.py", line 533, in bulk_write
    data, timeout)
  File "D:\Kyle\Python37\lib\site-packages\usb\backend\libusb0.py", line 616, in __write
    timeout
  File "D:\Kyle\Python37\lib\site-packages\usb\backend\libusb0.py", line 431, in _check
    raise USBError(errmsg, ret)
usb.core.USBError: [Errno None] b'libusb0-dll:err [_usb_reap_async] timeout error\n'
```

I assume this means it sending zero nsps? # Tinfoil USB List 0
There are nsps in the folder

**Comment by Zeromark30** [comment]
im an idiot did have it open to usb install.
